name: "Home Assistant S3 Backup"
description: "Backup your Home Assistant data to S3"
version: "1.0.0"
slug: "hassio_proton_drive_backup"
init: false
panel_title: S3 Backup
panel_icon: mdi:folder-upload
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
hassio_role: "backup"
ingress: true
map:
  - backup:rw
options:
  storage_backend: "S3"
  backup_directory: "Home Assistant Backups"
  log_level: Info
  proton:
    username: null
    password: null
  storj:
    access_grant: null
    bucket: home-assistant-backups
  s3:
    endpoint:
    bucket: home-assistant-backups
    access_key_id: null
    secret_access_key: null
schema:
  storage_backend: list(S3|Storj|Proton Drive)
  backup_directory: str
  log_level: match(Info|Debug|Warn|Error)
  proton:
    username: str
    password: password
  storj:
    access_grant: password
    bucket: str
  s3:
    endpoint: str
    bucket: str
    access_key_id: password
    secret_access_key: password
